server:
  port: 9000

spring:
  profiles:
    active: log,nacos-config,nacos-discovery
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-user
          uri: lb://admin-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1


