server:
  port: 9000

spring:
  application:
    name: spring-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        enabled: true
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        enabled: true
        file-extension: yml
        group: DEFAULT_GROUP
  profiles:
    active: dev

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG