server:
  port: 9000

spring:
  profiles:
    active: log,nacos-config,nacos-discovery
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: admin-user
              uri: lb://admin-user
              predicates:
                - Path=/user/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
